name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - uses: extractions/setup-just@v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Build Data(JSON)
        run: |
          pip install pyyaml
          just generate

      - name: Build Web
        run: |
          just web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/dist/
